version: "3.8"

services:
  backend:
    build: ./my-news-app-backend
    ports:
      - "8000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/news-app
    volumes:
      - ./my-news-app-backend:/app
      - /app/node_modules
    networks:
      - my_network

  frontend:
    build: ./my-news-app-frontend
    ports:
      - "5500:3000"  # Ajustado para React/Vite
    environment:
      - REACT_APP_NEWS_API_URL=http://localhost:8000/api/news
      - REACT_APP_ARCHIVED_API_URL=http://localhost:8000/api/news/archived
      - NODE_OPTIONS=--openssl-legacy-provider
    volumes:
      - ./my-news-app-frontend:/app
      - /app/node_modules  # Evita sobrescribir node_modules
    stdin_open: true
    tty: true
    networks:
      - my_network

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db  # Corregido aquí
      - ./data/initdb.js:/docker-entrypoint-initdb.d/initdb.js
    networks:
      - my_network

networks:
  my_network:

volumes:
  mongodb_data:  # Corregido aquí también
    driver: local
